account/urls.py
from django.urls import path

from . import views

urlpatterns = [

    path("register", views.register,name="register"),
    path("login", views.login,name="login"),
    path("logout", views.logout,name="logout")
     
]

bbbs/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    
    path('', include('bbbs1.urls')), ## 추가된 부분
    path('admin/', admin.site.urls),
    path('account/',include('account.urls')), ## 추가된 부분
   
     
]

bbbs1/urls.py
from django.contrib import admin
#from django.conf.urls import url
from django.urls import path, re_path
from bbbs1 import views 
 
 
urlpatterns = [
    re_path(r'^$', views.home, name='home'),
    re_path(r'^board/(?P<question_id>\d+)/$', views.question_detail, name='question_detail'), ## 추가 ##
    re_path(r'^board/question_create/$', views.question_create, name='question_create'), ## 추가 ##
    re_path(r'^board/answer_create/(?P<question_id>\d+)/$', views.answer_create, name='answer_create'),
    re_path(r'^board/question_modify/(?P<question_id>\d+)/$', views.question_modify, name='question_modify'),
    re_path(r'^board/question_delete/(?P<question_id>\d+)/$', views.question_delete, name='question_delete'),
    #url(r'^board/answer_modify/(?P<answer_id>\d+)/$', views.answer_modify, name='answer_modify'),
    #url(r'^boards/answer_delete/(?P<answer_id>\d+)/$', views.answer_delete, name='answer_delete'),
    re_path(r'^vote/question/(?P<question_id>\d+)/$', views.vote_question, name='vote_question'),
    #url(r'^vote/answer/(?P<answer_id>\d+)/$', views.vote_answer, name='vote_answer'),
    re_path(r'^user_search/$', views.user_search, name='user_search'), 
    re_path(r'^profile/$', views.profile, name='profile'), 
    


     
] 

account/models.py
from django.db import models

# Create your models here.

bbbs1/models.py
#from django.db import models

# Create your models here.
from django.db import models
from django.contrib.auth.models import User 


class Question(models.Model):
    subject = models.CharField(max_length=100)
    content = models.TextField()
    create_at = models.DateTimeField(auto_now_add=True)
    modify_at = models.DateTimeField(null=True, blank=True)
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='author_question') ## 수정 ##
    voter = models.ManyToManyField(User, related_name='voter_question')  ## 추가 ##
 
    def __str__(self):
        return self.subject

class Answer(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    content = models.TextField()
    create_at = models.DateTimeField(auto_now_add=True)
    author = models.ForeignKey(User, on_delete=models.CASCADE) # 추가
    modify_at = models.DateTimeField(null=True, blank=True) #추가
    #voter = models.ManyToManyField(User, related_name='voter_answer')

    def __str__(self):
        return self.content          

bbbs1/forms.py
from django import forms
from .models import Question, Answer 


class NewQuestionForm(forms.ModelForm):
## 해당 부분에 form에서 입력 받을 속성을 결정합니다. models.py와 동일하게 설정하면 됩니다. ##
    subject = forms.CharField(
        max_length=200,
        label='제목')
    content = forms.CharField(
        widget=forms.Textarea(),
        label='내용'
    )

## 어떤 모델을 사용하고 모델에서 사용할 속성을 지정 합니다 ##
    class Meta:
        model = Question
        fields = ['subject', 'content']

class AnswerForm(forms.ModelForm):
    content = forms.Textarea()

    class Meta:
        model = Answer
        fields = ['content',]

account/views.py
from django.shortcuts import render, redirect
from django.contrib import messages
from django.contrib.auth.models import User, auth


# Create your views here.

def register(request):

	if request.method == 'POST':

		first_name = request.POST[ 'first_name']
		last_name = request.POST[ 'last_name']
		username = request.POST[ 'username']
		password1 = request.POST[ 'password1']
		password2 = request.POST[ 'password2']
		email = request.POST[ 'email']

		user=User.objects.create_user(username=username, password=password1, email=email,first_name=first_name, last_name=last_name)
		user.save();
		#print('user created')
		return render(request, 'login.html') 

	else:
		return render(request, 'register.html')


def login(request):
	if request.method == 'POST':
		username = request.POST[ 'username']
		password = request.POST[ 'password']

		user = auth.authenticate(username=username,password=password)

		if user is not None:
			auth.login(request, user)
			return redirect("/")

		else:
			messages.info(request,'Invalid credential')
			return render(request, 'login.html');
		 

	else:
		return render(request, 'login.html');


def logout(request):
	auth.logout(request)
	return redirect("/")		
			 		

bbbs1/views.py
from django.shortcuts import get_object_or_404, render, redirect ## 추가된 부분
from .models import Question ## 추가된 부분
from django.utils import timezone
from .forms import NewQuestionForm, AnswerForm 
from django.core.paginator import Paginator 
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User

def home(request): 
    question_list = Question.objects.order_by('-create_at') 
    # 입력 파라미터
    page = request.GET.get('page','1')
     
    # 페이징처리
    paginator = Paginator(question_list, 7)
    page_obj = paginator.get_page(page)
    return render(request, 'home.html',{'question_list':page_obj})

     
     
@login_required(login_url='login')
def question_create(request):
    if request.method == 'POST':
        form = NewQuestionForm(request.POST)
        if form.is_valid():
            question = form.save(commit=False)
            question.create_at = timezone.now()

            question.author = request.user         ### 추가 ####

            question.save()
            return redirect('home')
    else:
        form = NewQuestionForm()
    return render(request, 'question_create.html', {'form':form})

def question_detail(request, question_id):
    question = get_object_or_404(Question,id=question_id)
    return render(request, 'view_question.html', {'question':question}) 

@login_required(login_url='login')
def question_modify(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    if request.user != question.author:
        messages.error(request, '수정권한이 없습니다')
        return redirect('question_detail', question_id=question_id)

    if request.method == 'POST':#form 채워 온 것을 받고  save 하고 나머지 author ,timezone 정해줌
        form = NewQuestionForm(request.POST, instance=question)
        if form.is_valid():
            question = form.save(commit=False)
            question.author = request.user
            question.modify_at = timezone.now()
            question.save()
            return redirect('question_detail', question_id=question_id)
    else:
        form = NewQuestionForm(instance=question)#question_create,html form에 question instance 넣어 보여줘라
        return render(request, 'question_create.html', {'form': form})


@login_required(login_url='login')
def question_delete(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    if request.user != question.author:
        messages.error(request, '삭제권한이 없습니다')
        return redirect('question_detail', question_id=question_id)
    question.delete()
    return redirect('home') 


def answer_create(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    if request.method == 'POST':
        form = AnswerForm(request.POST)
        if form.is_valid():
            answer = form.save(commit=False)
            answer.question = question
            answer.create_at = timezone.now()

            answer.author = request.user         ### 추가 ####
 
            answer.save()
            return redirect('question_detail',question_id=question_id)  

    else:
        form = AnswerForm()
    context = {'question':question,'form':form}
    return render(request, 'view_question.html',context) 

def vote_question(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    if request.user == question.author:
        messages.error(request, '자신이 작성한 글에는 추천할 수 없습니다.')
    else:
        question.voter.add(request.user)
    return redirect('question_detail', question_id=question_id) 


@login_required()
def user_search(request):

    subject = request.POST.get('subject', '').strip()
    
    question_search = Question.objects.filter(subject=subject)
     
    page = request.GET.get('page','1')
    paginator = Paginator(question_search, 4)
    question_search = paginator.get_page(page)
    return render(request, 'home.html',{'question_list':question_search})  


def profile(request):
    context = {'user': request.user}
    return render(request, 'profile.html', context)                                                   

templates/base.html
<!DOCTYPE html>
<html lang="ko">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>ANSWER 게시판</title>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js"></script>
 
<!-- 스크립트를 사용하기 위한 블록 선언 ###-->
  {% block script %}
  {% endblock %}

</head>

<body>
<nav class="navbar navbar-expand-md bg-light navbar-light border-bottom">
  <a class="navbar-brand" href="{% url 'home' %}">MYBBS</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#collapsibleNavbar">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="collapsibleNavbar">
    <ul class="navbar-nav">
      {% if user.is_authenticated %}
      <li>Hello, {{user}}</li>
      <li class="nav-item">
      <a class="nav-link" href="{% url 'profile' %}">Used Skill</a>
      </li>  
      <li class="nav-item">
        <a class="nav-link" href="/account/logout">로그아웃</a>
        </li>  
      {% else %}


         
      <li class="nav-item">
        <a class="nav-link" href="/account/register">회원가입</a>
      </li>

      <li class="nav-item">
        <a class="nav-link" href="/account/login">로그인</a>
      </li>

      {% endif %}  
       
    </ul>
  </div>


  </nav>
  <br>
  
 
{% block contents %}
{% endblock %}

</body>
</html>

templates/home.html
{% extends 'base.html' %}

{% block contents %}
<div class="container my-3">
 <table class="table">
 <thead class="thead-dark">
 <tr>
 <th>순서</th>
 <th>추천</th>
 <th>제목</th>
 <th>작성자</th>
 <th>작성일</th>

 </tr>
 </thead>
  <tbody>

 
 {% for question in question_list %}
   <tr>
   <td>{{ question.id }}</td>
   <td>{{ question.voter.count }}</td> 
     
   <td><a href="{% url 'question_detail' question.id %}">{{ question.subject }}</a>
    {% if question.answer_set.count > 0 %}
    <small class="text-danger ml-3">{{ question.answer_set.count }}</small>
   {% endif %} 

   </td>

  
   <!-- 수정 -->
   <td> {{ question.author }} </td>
  <!-- 수정 -->
    <td> {{ question.create_at }} </td>
    </tr>

 {% endfor %}

 {% include 'includes/paginator.html' %}
  </tbody>
  </table>
 
<!--## 추가 ## -->
<a href="{% url 'question_create' %}" class="btn btn-primary float-right">질문 등록</a> 

<form class="form-inline" method="post" action="{% url 'user_search' %}">
  <!-- navbar-form avoid CSRF verification failed error. -->
  {% csrf_token %}
<div class="form-group">
  <input name="subject" type="text" placeholder="BBS Title" class="form-control" value="{{ search_subject }}">
</div>
<button type="submit" class="btn btn-success">Search</button>

</form>





</div>




{% endblock %}
  

templates/includes/paginator.html
<!-- 첫페이지로 돌아가기 -->
<nav aria-label="pagination" class="mb-4">
    <ul class="pagination justify-content-center">
   {% if question_list.number > 1 %}
   <li class="page-item">
   <a class="page-link" href="?page=1">처음</a>
   </li>
   {% else %}
   <li class="page-item disabled">
   <span class="page-link">처음</span>
   </li>
   {% endif %}
   
    <!-- 이전 페이지 구현-->
   {% if question_list.has_other_pages %}
     {% if question_list.has_previous %}
     <li class="page-item">
        <a class="page-link" href="?page={{ question_list.previous_page_number }}">이전</a>
     </li>
     {% else %}
     <li class="page-item disabled">
      <span class="page-link">이전</span>
     </li>
     {% endif %}
   
   <!-- 페이징 구현-->
    {% for page_num in question_list.paginator.page_range %}
     {% if question_list.number == page_num %}
     <li class="page-item active">
      <span class="page-link">{{ page_num }}
       <span class="sr-only">(current)</span>
      </span>
     </li>
     {% elif page_num > question_list.number|add:'-4' and page_num < question_list.number|add:'4' %}
     <li class="page-item">
      <a class="page-link" href="?page={{ page_num }}">{{ page_num }}</a>
     </li>
     {% endif %}
   {% endfor %}
   
    <!-- 다음 페이지 구현-->
     {% if question_list.has_next %}
     <li class="page-item">
        <a class="page-link" href="?page={{ question_list.next_page_number }}">다음</a>
     </li>
     {% else %}
     <li class="page-item disabled">
      <span class="page-link">다음</span>
     </li>
     {% endif %}
   {% endif %}
   
   <!-- 끝으로 돌아가기 -->
    {% if question_list.number != question_list.paginator.num_pages %}
    <li class="page-item">
      <a class="page-link" href="?page={{ question_list.paginator.num_pages }}">끝</a>
    </li>
    {% else %}
    <li class="page-item disabled">
      <span class="page-link">끝</span>
    </li>
    {% endif %}
   </ul>
   </nav>

templates/login.html
{% extends 'base.html' %}

{% block contents %}

<title>Registration</title>
</head>
<body>
	<form action="login" method="post">
		{% csrf_token %}

		<input type="text" name="username" placeholder="username"><br>
		<input type="password" name="password" placeholder="password"><br>
		<input type="Submit">

	</form>

	<div>
		{% for message in messages %}	
		<h3>{{message}}</h3>
		{% endfor %}
	</div>

	{% endblock %}	

templates/profile.html
{% extends "base.html" %}


{% block contents %}
    {% load static %}
    <link rel="stylesheet" type='text/css' href="#">

    <div class="content">
        <div id="profile_title">
            <h3>사용된 기술(Used Skill)</h3>
        </div><br>
       
        <div id="profile_main">
            <ul>
                <li>
                    <h3>
                        <a href="#">
                            <strong>@질문 등록</strong>
                        </a>
                    </h3>
                    @views.py 에서 아래 coding으로 질문 등록시 login.html로 가서 log in 먼저 하도록 함.
                    <br>from django.contrib.auth.decorators import login_required
                    <br>@login_required(login_url='login')<br>
                    <br>'question_create.html'에서 summernote- lite with cdn link를 사용해서 입력 폼을 사치화
                    <br><!--  <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
                    <link href="https://cdn.jsdelivr.net/npm/summernote@0.8.18/dist/summernote-lite.min.css" rel="stylesheet">
                    <script src="https://cdn.jsdelivr.net/npm/summernote@0.8.18/dist/summernote-lite.min.js"></script>
                    -->
                    summernote- lite는 따로 설치할 것없이 이렇게 코딩(hidden in this page)을 하면 된다 
                    <br>###########################################################################
                    <br>@views.py 에서 def question_create(request):
                    <br>if request.method == 'POST':
                    <br>form = NewQuestionForm(request.POST)
                    <br>if form.is_valid():
                    <br>question = form.save(commit=False)
                    <br>save(commit=False) 왜 사용하나요?
                    <br>commit=False를 하게 되면 데이터베이스에 당장 저장하지 않는다.
                    <br>언제쓰지? : DB에 데이터를 저장하기 전에 특정 행위를 하고 싶을 때 사용한다
                    <br><br>question.save()
                    <br>return redirect('home')
                    <br>아래 2개는 Form에 없는 fields로 별도로 저장이 필요하므로 추가한 것 
                    <br>question.author = request.user
                    <br>question.create_at = timezone.now()
                    <br>###########################################################################
                    <br>POST한 것이 없는 상태에서는 form = NewQuestionForm()을 불러 입력하려면 else: 로 
                    <br>question.create_at = timezone.now()
                    <br>return render(request, 'question_create.html', {'form':form})

                    
                </li><br><br>
                <li>
                    <h3>
                        <a href="...">
                            <strong>@질문 삭제</strong>
                        </a>
                    </h3>
                    @views.py<br>from django.shortcuts import get_object_or_404
                    <br>def question_delete(request, question_id)
                    <br>삭제하려면 details에서 삭제하려는 id를 가져오고
                    <br>question = get_object_or_404(Question, pk=question_id)
                    <br>해당 object를 지정한 후 삭제    
                    <br>question.delete() 
                    <br>detail 전의 화면으로 여기서는 home으로 redirect
                    <br>return redirect('home')
                    <br>if request.user != question.author:
                    <br>로그인 한 user가 게시물의 author일 경우만 삭제가능( model에 저장된 author)
                    <br>messages.error(request, '삭제권한이 없습니다')
                    <br>return redirect('question_detail', question_id=question_id)
                    <br>왔던 곳으로 돌림.

                </li><br><br>

                <br>##########################################################################################################

                <li>
                    <h3>
                        <a href="...">
                            <strong>@질문 수정</strong>
                        </a>
                    </h3>
                    @views.py<br>def question_modify(request, question_id):
                    <br>해당 id를 가져오고 해당 object를 지정
                    <br>if request.method == 'POST':#form 채워 온 것을 받고  save 하고 나머지 author ,timezone 정해줌
                    <br>form = NewQuestionForm(request.POST, instance=question)
                    <br>수정이므로 모델에 어떤 class를 수정할 것인지 그 instance를 정해주어야 한다.
                    <br>if form.is_valid():    
                    <br>question = form.save(commit=False)
                    <br>question.save()
                    <br>detail화면으로 가서 수정을 보여줌
                    <br>return redirect('question_detail', question_id=question_id)
                    <br>아래 2개는 Form에 없는 fields로 별도로 저장이 필요하므로 추가한 것 
                    <br>question.author = request.user
                    <br>question.modify_at = timezone.now() 
                    <br>###########################################################################
                    <br>else: 폼으로 내용 수정먼저 하도록
                    <br>form = NewQuestionForm(instance=question)#question_create,html form에 question instance 넣어
                    <br>return render(request, 'question_create.html', {'form': form}): create 경우와같은 폼 사용
                    <br>이것은 question_create.html에서  form method="post">와 같이 POST url을 비워나서 가능
                    <br>###########################################################################
                    <br>로그인 한 user가 게시물의 author일 경우만 삭제가능( model에 저장된 author)
                    <br>messages.error(request, '삭제권한이 없습니다')
                    <br>return redirect('question_detail', question_id=question_id)
                    <br>왔던 곳으로 돌림.

                </li><br><br>

                <br>##########################################################################################################

                <li>
                    <h3>
                    <a href="...">
                        <strong>질문영역 추천</strong>
                    </a>
                    </h3>

                    @view_question.html<br>해당 question.id를 추천하는 링크 생성
                    <br>a href="% url 'vote_question' question.id %"추천
                    <br>def vote_question(request, question_id):
                    <br>question = get_object_or_404(Question, pk=question_id)
                    <br>해당 object를 꺼내서
                    <br>question.voter.add(request.user) 
                    <br>voter = models.ManyToManyField(User, related_name='voter_question')  
                    <br>question.voter은 모델에서 User이므로 add(User)는 vote_question할 때마다 User가 더해짐.
                    <br>다대다 관계란 피자(question)와 토핑(voter)관계처럼 한 피자에 여러 토핑을 올리는 구조에 사용
                    <br>ManyToManyField는 데이터베이스 수준에서 다대다 관계를 표현하기 위해 별도의 테이블을 사용합니다 
                    <br>PG Admin에 들어가 보면 bbbs1_question_voter는 bbbs1_question과 별도의 테이블이 생성되어 있다.
                    
                    <br>페이지를 돌려주고
                    <br>return redirect('question_detail', question_id=question_id) 
                    <br>@view_question.html: question.voter.count이 추천 갯수 태그에 보여지게함

                </li><br><br>

                <br>##########################################################################################################

                <li>
                    <h3>
                    <a href="...">
                        <strong>Paginator</strong>
                    </a>
                    </h3>

                    template>includes>paginator.html  생성
                    <br>question_list = Question.objects.order_by('-create_at') 
                    <br>model class Question인 경우이고 question_list가 아닌 경우 replace all @paginator.html 
                    <br>@home.html 
                    <br>% include 'includes/paginator.html' %
                    <br>@def home(request): 이와같이 해서 한 페이지에 나타낼 게시물의 수를 정해줄 수 있다.
                
                </li><br><br>
                
                <br>##########################################################################################################

                <li>
                    <h3>
                    <a href="...">
                        <strong>Search</strong>
                    </a>
                    </h3>

                    @link html - @home.html
                    <br>form을 써서 url 'user_search'로 보냄
                    <br>form class="form-inline" method="post" action="% url 'user_search' %"
                    <br>search_subject는 "subject"로 search 하겠다는 것
                    <br>value=" search_subject "

                    <br>@views-user_search
                    <br>form에서 넣었던  subject를 POST.get으로 가져옴 
                    <br>subject = request.POST.get('subject', '').strip() 
                    <br>question_search = Question.objects.filter(subject=subject)
                    <br>question_search를 paginator 적용해서 결과를 보여주는 page로 보냄
                    <br>return render(request, 'home.html',{'question_list':question_search})  
                
                </li><br><br>

                <br>##########################################################################################################

                <li>
                    <h3>
                    <a href="...">
                        <strong>답변 등록</strong>
                    </a>
                    </h3>

                    @view_question.html<br>해당 question.id에 답을 다는 링크 생성
                    <br>form action="% url 'answer_create' question.id %" method="post"
                    <br>textarea name="content" id="content" class="form-control" rows="10"
                    <br>Submit
                    <br>@view - answer_create
                    <br>else: AnswerForm() 채우기 여기서는 modelforms가 아니라 html 입력 form

                    <br>question = get_object_or_404(Question, pk=question_id)
                    <br>question_id에 맞는 object를 지정해야 나중에 view_question.html에 보여주어야 하니까
                    <br>return render(request, 'view_question.html',context)  

                    <br>그리고 나머지는 question create와 같다.
                    <br>###########################################################################
                    <br>@view_question.html에서 answer의 내용을 보여주기 위해
                    <br>for answer in question.answer_set.all
                    <br>answer 데이터를 question에서 찾을 때 in question.answer_set.all
                    <br>answer.content/answer.author/answer.create_at

                </li><br><br>

            <br>##########################################################################################################

                <li>
                    <h3>
                    <a href="...">
                        <strong>Url에서 이것 안된다  #from django.conf.urls import url
</strong>
                    </a>
                    </h3>

                    from django.urls import path, re_path
                    <br>path를 쓰거나
                    <br>url(r'^board/answer_modi...대신
                    <br>re_path(r'^board/answer_modi...로 바꾸어 주어야
                    
                
                </li><br><br>
                    









            </ul>
        </div>
    </div>


{% endblock %}

templates/question_create.html
{% extends 'base.html' %}
 

{% block contents %}

    <div class="container">
        <h5 class="my-3 border-bottom pb-2">질문등록</h5>
        <form method="post">
        {% csrf_token %}

    
     <div class="form-group">
         <label for="subject">제목</label>
         <input type="text" class="form-control" name="subject" id="subject"
                value="{{ form.subject.value|default_if_none:'' }}">
     </div>


     <div class="form-group">
        <label for="content">내용</label>
        <textarea id="summernote" name="content">
        {{ form.content.value|default_if_none:'' }}</textarea>
    </div>

        
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <link href="https://cdn.jsdelivr.net/npm/summernote@0.8.18/dist/summernote-lite.min.css" rel="stylesheet">
    <script src="https://cdn.jsdelivr.net/npm/summernote@0.8.18/dist/summernote-lite.min.js"></script>
  
    <div id="summernote"></div>
    <script>
      $('#summernote').summernote({
        placeholder: 'Hello stand alone ui',
        tabsize: 2,
        height: 120,
        toolbar: [
          ['style', ['style']],
          ['font', ['bold', 'underline', 'clear']],
          ['color', ['color']],
          ['para', ['ul', 'ol', 'paragraph']],
          ['table', ['table']],
          ['insert', ['link', 'picture', 'video']],
          ['view', ['fullscreen', 'codeview', 'help']]
        ]
      });
    </script>
  
    <button type="submit" class="btn btn-primary">저장하기</button>
    <a href="{%url 'home'%}" class="btn btn-secondary">돌아가기</a>
    </form>
</div>


<!-- 오류표시 Start -->
{% if form.errors %}
<div class="alert alert-danger" role="alert">
{% for field in form %}
    {% if field.errors %}
    <strong>{{ field.label }}</strong>
    {{ field.errors }}
    {% endif %}
{% endfor %}
</div>
{% endif %}
<!-- 오류표시 End -->

{% endblock %}

templates/register.html
{% extends 'base.html' %}

{% block contents %}


<form action="register" method="post">
    
    {% csrf_token %}

    <input type="text" name="first_name" placeholder="First Name"><br>
    <input type="text" name="last_name" placeholder="Last Name"><br>
    <input type="text" name="username" placeholder="Username"><br>
    <input type="email" name="email" placeholder="email"><br>
    <input type="password" name="password1" placeholder="Password"><br>
    <input type="password" name="password2" placeholder="Confirm Password"><br>
    <input type="Submit">

</form>

<div>
    {% for message in messages %}	
    <h3>{{message}}</h3>
    {% endfor %}
</div>


{% endblock %}

templates/view_question.html
{% extends 'base.html' %}
 

{% block contents %}

<div class="container mt-3">
    <h2 class="border-bottom py-2">{{ question.subject }}</h2>

 <!-- ###################### 질문 영역 ###################### -->
   <!-- 질문영역 추천영역 -->
   <div class="row my-3">
    <div class="col-1"> 
        <div class="bg-light text-center p-3 border font-weight-bolder mb-1">{{question.voter.count}}</div>
        <a href="{% url 'vote_question' question.id %}"
        class="btn btn-sm btn-secondary btn-block my-1">추천</a>
    </div>
  <!-- 질문영역 추천영역 -->
  
  <!-- 질문 본문영역 -->
    <div class="col-11 ">
     <div class="card">
    <div class="card-body">
     <div class="card-text">{{ question.content|safe}}</div>
   
  </div>
  </div>
  <!-- 질문 본문영역 -->
  
 
 
<!--<div class="container my-3">

 <h5>{{ question.subject }}</h5>
 <p>{{ question.content|safe}}</p>-->

  

 {% if question.modify_at %}
    <div>수정일: {{ question.modify_at }}</div>
    <div>작성일: {{ question.create_at }}</div>
    {% else %}
    <div>작성일: {{ question.create_at }}</div>
    {% endif %}

    <h5 class="border-bottom my-3 py-2">{{question.answer_set.count}}개의 답변이 있습니다.</h5>

    <form action="{% url 'answer_create' question.id %}" method="post" class="my-3">

 
        {% csrf_token %}
      
        {% for answer in question.answer_set.all %}
        <div class="card my-3">
         <div class="card-body">
          <div class="card-text" style="white-space: pre-line;">{{ answer.content }}</div>
          <br>
          <div><h6>작성일:{{ answer.create_at}}</h6></div>
          <div><h6>작성자:{{ answer.author}}</h6></div>
        
        </div>
        </div> 
      
        {% endfor %} 
        
        
     <!-- 오류표시 Start -->
     {% if form.errors %}
     <div class="alert alert-danger" role="alert">
     {% for field in form %}
         {% if field.errors %}
         <strong>{{ field.label }}</strong>
         {{ field.errors }}
         {% endif %}
     {% endfor %}
     </div>
    {% endif %}

    <div class="form-group">
        <textarea name="content" id="content" class="form-control" rows="10"></textarea>
    </div>
    <input type="submit" value="답변등록" class="btn btn-primary">




<a href="{% url 'home' %}" class="btn btn-secondary">돌아가기</a>
<a href="{% url 'question_modify' question.id %}" class="btn btn-sm btn-outline-secondary">수정</a>
 
<a href="{% url 'question_delete' question.id %}"
       class="delete btn btn-sm btn-outline-info">삭제</a>

<!--<a href=# data-uri="{% url 'question_delete' question.id %}"
class="delete btn btn-sm btn-outline-info">삭제</a>-->

 
{% endblock %}

 
 
       

 
 





 
 